### ISSUE TITLE
Add a "Recently Updated" filter 

### ISSUE THREAD

**Issue by Zabooby** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#220]
With so many themes now on the store I think it would be great to be able to filter by "recently updated", so users can find working themes much quicker.

A filter in the search settings to sort themes by how recently then were updated. 

Just did a quick review myself and here are a few themes that have been archived/no longer exist: 
https://github.com/c2oc/FirefoxCSS-Plus
https://github.com/Ikrom27/Firefox
https://github.com/k-amryn/quietfox
https://github.com/fellowish/firefox-review
https://github.com/akshat46/FlyingFox

Also here are some that haven't been updated in ~4 years:
https://github.com/mut-ex/minimal-functional-fox
https://github.com/eromatiya/blurredfox

**Comment by BeyondMagic** [comment]
A quick notice, this feature cannot be dynamic due to two reasons:
1. the site is not a server, it is only a HTML/JS/CSS renderer.
2. due to the site not being a server, we can't check all of the repositories and their last updated time in a performant way.

However, we can make a script that can run daily/weekly/monthly that will create a new database file sorted by the latest commit in each repository, and then on the site we can switch to it, thus having this feature.

**Comment by Zabooby** [comment]
> A quick notice, this feature cannot be dynamic due to two reasons:
> 
>     1. the site is not a server, it is only a HTML/JS/CSS renderer.
> 
>     2. due to the site not being a server, we can't check all of the repositories and their last updated time in a performant way.
> 
> 
> However, we can make a script that can run daily/weekly/monthly that will create a new database file sorted by the latest commit in each repository, and then on the site we can switch to it, thus having this feature.

Monthly sounds good, anything shorter is probably excessive. Firefox doesn't break css themes _that_ often.
