### ISSUE TITLE
images to webp

### ISSUE THREAD

**Issue by Neikon** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#24]
I find this https://github.com/1000ch/gulp-cwebp 
It could be added to our workflow to automatically convert our images, with a 2º github action or in the one we already have

maybe we could make it run automatically when there are changes in the "theme.json" file.

the only inconvenient is that we must remember to include in the "theme.json" the url of the image already with the ".webp". if I am not mistaken.

**Comment by andreasgrafen** [comment]
Yeah! That's a nice tool; great find. I've added it into the gulp workflow to convert images automatically and copy them to `/docs/assets/img/*` on `build`.

What is slightly annoying is the manual work required…
- grab the image that is originally submited by the author
- download it
- add it to the repo
- `build`
- update the path in `themes.json`
- commit all this

I'm sure this can be automated, I just don't know how that would be done via Actions. :c

**Comment by BeyondMagic** [comment]
I think, correct me if I'm wrong, that we can use a **shell** script, add some **cat** with **grep/sed** and **wget/curl** to get the images that are links and then run the script to transform them into **webp**, then change the file with **grep**; the question is if **Github Action** can do that, if not, the script alone would already make faster the process, we could run it after adding a new theme.

**Comment by andreasgrafen** [comment]
Jeebus.. I'm a dumbo. For some reason I was so fixated on Node that I totally forgot about the simplicity of shell scripting. D:

Besides that I'm also trying to get the json validation we currently have in our main.js into a seperate unit test that we can run with Node in an Action to automatically check for the correct format/syntax on pull requests. c:

**Comment by Neikon** [comment]
we can 
![imagen](https://user-images.githubusercontent.com/1765319/106822964-6a49ca80-6680-11eb-947a-3af2729c0ab9.png)
https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#adding-scripts-to-your-workflow

**Comment by BeyondMagic** [comment]
[shell-add](/FirefoxCSS-Store/FirefoxCSS-Store.github.io/tree/shell-add/tests/img-switch.sh) has the script, I don't know exactly how to add the script in the workflow and then run the build, but the script is working fine, howver it depends on `grep, sed, wget, mogrify (imagemagick)` to work, I don't thiink Github Actions gives permission to some of those commands, lol.

**Comment by andreasgrafen** [comment]
**holy**. This script is amazing. It's so fast! ♡

We could get rid of the last one since our `gulp` workflow already allows for conversion to `webp` anyway. Therefore it wouldn't matter when the downloaded file in `/images/themes` is `.jpg` or `.png`.
The rest is pretty much standard software. It would be worth checking if Actions allows us to use them. c:

**Comment by BeyondMagic** [comment]
Yeah, I had to get around that with this solution because of the names and extensions, if you tried to add a example theme in `/themes.json` and then run the script, you'd see that the image passed to `/images/themes/` is a number (18~19) and has webp as file extension, the problem with `wget` is that it doesn't preserve the file extension when downloading and renaming, so I had to use `imagemagick:mogrify` to identify the file extension (whatever it is png or jpg) and then parse to webp, and I had to change the name because some images can come with parameters, like, idk, `fish.png?we=w&lw=kk...`.

And the numbers must be numbers because, well, we could get the title above the image link with `B3` in grep, but, this is out of my hands, right now, I don't have idea on how to start with that.

- [ ] verify if there's a new theme link and if there isn't, then doesn't run the script

**Comment by andreasgrafen** [comment]
But doesn't using `wget #LINK#` without the `-O` flag just save the file with the original name and file extension?
Imma tinker around with this on my own real quick. :D

**Comment by BeyondMagic** [comment]
If the gulp webp is capable of identifying files like `fish.png?we=w&k=l....`, then, yes. But mogrify is really small and fast, and it seems more organized when using numbers in my opinion, it already does everything lol.

**Comment by andreasgrafen** [comment]
I've just realised that I need to learn a lot more about the simple things like `sed` :D

Removing URL parameters isn't actually so much of a change – well, if I understood this correctly at least. This should do the trick `[…] | sed -e 's/?.*//g'` as it matches the `?` and removes everything that is following as well.
To get a clean file name this ugly piece of regex could come in handy: `[^/?#]*\.[^/?#]*(\?.*)?(\#.*)?$`

I don't know if that helps and my brain is too mushy right now to actually craft a script out of this. But I'll leave this here anyway either for you or later use for me. :D

**Comment by BeyondMagic** [comment]
Yeah, I'll add it and minimize the current script tomorrow

**Comment by andreasgrafen** [comment]
Awesome! I can't even fully comprehend what all the things in your script actually do right now, this it's probably better that way. :D

**Comment by BeyondMagic** [comment]
Ok, sorry for being so late, but the [script](/FirefoxCSS-Store/FirefoxCSS-Store.github.io/tree/shell-add/tests/img-switch.sh) seems to work perfectly fine now. You can try it, it's using the pure basic commands of GNU unix, so I think it can works on the workflow, if not, like I said, it's way faster now to build the image of new theme s:)

**Comment by BeyondMagic** [comment]
Closed with fe0d1d6b3c78424c80b21fedfff84f5c94d8eaec and ff3f65e83153e703b2032d9093f8a0b3af29aad1. The build workflow is merged now with the script, you just have to run it after a new theme is added. Thanks to @Neikon with the gulp webp and @andreasgrafen for the help.
