### ISSUE TITLE
Make images expandable

### ISSUE THREAD

**Issue by LongJohn-Silver** [FirefoxCSS-Store/FirefoxCSS-Store.github.io#91]
**Is your feature request related to a problem? Please describe.**

Right now it is necessary to go to each theme's repository in order to preview them.

**Describe the solution you'd like**

If one could click the images to expand them and be able to appreciate how the theme looks without leaving the store, it would be a more comfortable experience in order to decide which one to choose.

**Describe alternatives you've considered**

N/A.

**Additional context**

The link to the repository could be contained within the theme's name, or in a GitHub, Gitlab, etc logo inside the drop down menu.

**Comment by andreasgrafen** [comment]
I finally found some time to get to this!

I've created a feature branch with a **dead simple** lightbox solution – it def. isn't anything fancy.
When a card is hovered the user will now see two extra buttons. One to **Enlarge** the image one one do get to the repo. I've chosen not to make the lightbox the default behaviour on click because I believe that the main intention of most users is to actually get to the coresponding repo. The **Download** button is basically just for clarity, but clicking the card directly still opens the repo-link.

I've put a [demo on my personal site](https://andreas.grafen.info/other/ffcss/lightbox/) but feel free to run it yourself locally as well. :b

I'm looking forward to your critiques @LongJohn-Silver @Neikon c:

**Comment by Neikon** [comment]
I like it.

**Comment by andreasgrafen** [comment]
Nice. c:
**Quick update**: It now also works properly with keyboard navigation.

**Comment by LongJohn-Silver** [comment]
@andreasgrafen hey sorry for taking so long to reply, thisblooks really awesome! Thanks a lot for this!

**Comment by andreasgrafen** [comment]
No worries. I took ages to respond as well. 
Glad you like it! c:
